
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `countries` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `phone` bigint(20) UNSIGNED NOT NULL,
  `code` varchar(3) COLLATE utf8mb4_unicode_ci NOT NULL,
  `country_flag` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `symbol` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `capital` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `currency_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `currency` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `continent` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `continent_code` varchar(2) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `alpha_3` varchar(3) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



INSERT INTO `countries` (`id`, `phone`, `code`, `country_flag`, `name`, `symbol`, `capital`, `currency_name`, `currency`, `continent`, `continent_code`, `alpha_3`, `created_at`, `updated_at`) VALUES
(1, 93, 'AF', 'af', 'Afghanistan', '؋', 'Kabul', 'Afghani', 'AFN', 'Asia', 'AS', 'AFG', NULL, NULL),
(2, 358, 'AX', 'ax', 'Aland Islands', '€', 'Mariehamn', 'Euro', 'EUR', 'Europe', 'EU', 'ALA', NULL, NULL),
(3, 355, 'AL', 'al', 'Albania', 'Lek', 'Tirana', 'Lek', 'ALL', 'Europe', 'EU', 'ALB', NULL, NULL),
(4, 213, 'DZ', 'dz', 'Algeria', 'دج', 'Algiers', 'Algerian Dinar', 'DZD', 'Africa', 'AF', 'DZA', NULL, NULL),
(5, 1684, 'AS', 'as', 'American Samoa', '$', 'Pago Pago', 'US Dollar', 'USD', 'Oceania', 'OC', 'ASM', NULL, NULL),
(6, 376, 'AD', 'ad', 'Andorra', '€', 'Andorra la Vella', 'Euro', 'EUR', 'Europe', 'EU', 'AND', NULL, NULL),
(7, 244, 'AO', 'ao', 'Angola', 'Kz', 'Luanda', 'Kwanza', 'AOA', 'Africa', 'AF', 'AGO', NULL, NULL),
(8, 1264, 'AI', 'ai', 'Anguilla', '$', 'The Valley', 'East Caribbean Dollar', 'XCD', 'North America', 'NA', 'AIA', NULL, NULL),
(9, 672, 'AQ', 'aq', 'Antarctica', '$', 'Antarctica', '', 'AAD', 'Antarctica', 'AN', 'ATA', NULL, NULL),
(10, 1268, 'AG', 'ag', 'Antigua and Barbuda', '$', 'St. John\'s', 'East Caribbean Dollar', 'XCD', 'North America', 'NA', 'ATG', NULL, NULL),
(11, 54, 'AR', 'ar', 'Argentina', '$', 'Buenos Aires', 'Argentine Peso', 'ARS', 'South America', 'SA', 'ARG', NULL, NULL),
(12, 374, 'AM', 'am', 'Armenia', '֏', 'Yerevan', 'Armenian Dram', 'AMD', 'Asia', 'AS', 'ARM', NULL, NULL),
(13, 297, 'AW', 'aw', 'Aruba', 'ƒ', 'Oranjestad', 'Aruban Florin', 'AWG', 'North America', 'NA', 'ABW', NULL, NULL),
(14, 61, 'AU', 'au', 'Australia', '$', 'Canberra', 'Australian Dollar', 'AUD', 'Oceania', 'OC', 'AUS', NULL, NULL),
(15, 43, 'AT', 'at', 'Austria', '€', 'Vienna', 'Euro', 'EUR', 'Europe', 'EU', 'AUT', NULL, NULL),
(16, 994, 'AZ', 'az', 'Azerbaijan', 'm', 'Baku', 'Azerbaijan Manat', 'AZN', 'Asia', 'AS', 'AZE', NULL, NULL),
(17, 1242, 'BS', 'bs', 'Bahamas', 'B$', 'Nassau', 'Bahamian Dollar', 'BSD', 'North America', 'NA', 'BHS', NULL, NULL),
(18, 973, 'BH', 'bh', 'Bahrain', '.د.ب', 'Manama', 'Bahraini Dinar', 'BHD', 'Asia', 'AS', 'BHR', NULL, NULL),
(19, 880, 'BD', 'bd', 'Bangladesh', '৳', 'Dhaka', 'Taka', 'BDT', 'Asia', 'AS', 'BGD', NULL, NULL),
(20, 1246, 'BB', 'bb', 'Barbados', 'Bds$', 'Bridgetown', 'Barbados Dollar', 'BBD', 'North America', 'NA', 'BRB', NULL, NULL),
(21, 375, 'BY', 'by', 'Belarus', 'Br', 'Minsk', 'Belarusian Ruble', 'BYN', 'Europe', 'EU', 'BLR', NULL, NULL),
(22, 32, 'BE', 'be', 'Belgium', '€', 'Brussels', 'Euro', 'EUR', 'Europe', 'EU', 'BEL', NULL, NULL),
(23, 501, 'BZ', 'bz', 'Belize', '$', 'Belmopan', 'Belize Dollar', 'BZD', 'North America', 'NA', 'BLZ', NULL, NULL),
(24, 229, 'BJ', 'bj', 'Benin', 'CFA', 'Porto-Novo', 'CFA Franc BCEAO', 'XOF', 'Africa', 'AF', 'BEN', NULL, NULL),
(25, 1441, 'BM', 'bm', 'Bermuda', '$', 'Hamilton', 'Bermudian Dollar', 'BMD', 'North America', 'NA', 'BMU', NULL, NULL),
(26, 975, 'BT', 'bt', 'Bhutan', 'Nu.', 'Thimphu', 'Indian Rupee', 'BTN', 'Asia', 'AS', 'BTN', NULL, NULL),
(27, 591, 'BO', 'bo', 'Bolivia', 'Bs.', 'Sucre', 'Boliviano', 'BOB', 'South America', 'SA', 'BOL', NULL, NULL),
(28, 599, 'BQ', 'bq', 'Bonaire, Sint Eustatius and Saba', '$', 'Kralendijk', 'US Dollar', 'USD', 'North America', 'NA', 'BES', NULL, NULL),
(29, 387, 'BA', 'ba', 'Bosnia and Herzegovina', 'KM', 'Sarajevo', 'Convertible Mark', 'BAM', 'Europe', 'EU', 'BIH', NULL, NULL),
(30, 267, 'BW', 'bw', 'Botswana', 'P', 'Gaborone', 'Pula', 'BWP', 'Africa', 'AF', 'BWA', NULL, NULL),
(31, 55, 'BV', 'bv', 'Bouvet Island', 'kr', '', 'Norwegian Krone', 'NOK', 'Antarctica', 'AN', 'BVT', NULL, NULL),
(32, 55, 'BR', 'br', 'Brazil', 'R$', 'Brasilia', 'Brazilian Real', 'BRL', 'South America', 'SA', 'BRA', NULL, NULL),
(33, 246, 'IO', 'io', 'British Indian Ocean Territory', '$', 'Diego Garcia', 'US Dollar', 'USD', 'Asia', 'AS', 'IOT', NULL, NULL),
(34, 673, 'BN', 'bn', 'Brunei Darussalam', 'B$', 'Bandar Seri Begawan', 'Brunei Dollar', 'BND', 'Asia', 'AS', 'BRN', NULL, NULL),
(35, 359, 'BG', 'bg', 'Bulgaria', 'Лв.', 'Sofia', 'Bulgarian Lev', 'BGN', 'Europe', 'EU', 'BGR', NULL, NULL),
(36, 226, 'BF', 'bf', 'Burkina Faso', 'CFA', 'Ouagadougou', 'CFA Franc BCEAO', 'XOF', 'Africa', 'AF', 'BFA', NULL, NULL),
(37, 257, 'BI', 'bi', 'Burundi', 'FBu', 'Bujumbura', 'Burundi Franc', 'BIF', 'Africa', 'AF', 'BDI', NULL, NULL),
(38, 855, 'KH', 'kh', 'Cambodia', 'KHR', 'Phnom Penh', 'Riel', 'KHR', 'Asia', 'AS', 'KHM', NULL, NULL),
(39, 237, 'CM', 'cm', 'Cameroon', 'FCFA', 'Yaounde', 'CFA Franc BEAC', 'XAF', 'Africa', 'AF', 'CMR', NULL, NULL),
(40, 1, 'CA', 'ca', 'Canada', '$', 'Ottawa', 'Canadian Dollar', 'CAD', 'North America', 'NA', 'CAN', NULL, NULL),
(41, 238, 'CV', 'cv', 'Cape Verde', '$', 'Praia', '', 'CVE', 'Africa', 'AF', 'CPV', NULL, NULL),
(42, 1345, 'KY', 'ky', 'Cayman Islands', '$', 'George Town', 'Cayman Islands Dollar', 'KYD', 'North America', 'NA', 'CYM', NULL, NULL),
(43, 236, 'CF', 'cf', 'Central African Republic', 'FCFA', 'Bangui', 'CFA Franc BEAC', 'XAF', 'Africa', 'AF', 'CAF', NULL, NULL),
(44, 235, 'TD', 'td', 'Chad', 'FCFA', 'N\'Djamena', 'CFA Franc BEAC', 'XAF', 'Africa', 'AF', 'TCD', NULL, NULL),
(45, 56, 'CL', 'cl', 'Chile', '$', 'Santiago', 'Chilean Peso', 'CLP', 'South America', 'SA', 'CHL', NULL, NULL),
(46, 86, 'CN', 'cn', 'China', '¥', 'Beijing', 'Yuan Renminbi', 'CNY', 'Asia', 'AS', 'CHN', NULL, NULL),
(47, 61, 'CX', 'cx', 'Christmas Island', '$', 'Flying Fish Cove', 'Australian Dollar', 'AUD', 'Asia', 'AS', 'CXR', NULL, NULL),
(48, 672, 'CC', 'cc', 'Cocos (Keeling) Islands', '$', 'West Island', 'Australian Dollar', 'AUD', 'Asia', 'AS', 'CCK', NULL, NULL),
(49, 57, 'CO', 'co', 'Colombia', '$', 'Bogota', 'Colombian Peso', 'COP', 'South America', 'SA', 'COL', NULL, NULL),
(50, 269, 'KM', 'km', 'Comoros', 'CF', 'Moroni', 'Comorian Franc ', 'KMF', 'Africa', 'AF', 'COM', NULL, NULL),
(51, 242, 'CG', 'cg', 'Congo', 'FC', 'Brazzaville', 'Congolese Franc', 'XAF', 'Africa', 'AF', 'COG', NULL, NULL),
(52, 242, 'CD', 'cd', 'Congo, Democratic Republic of the Congo', 'FC', 'Kinshasa', '', 'CDF', 'Africa', 'AF', 'COD', NULL, NULL),
(53, 682, 'CK', 'ck', 'Cook Islands', '$', 'Avarua', 'New Zealand Dollar', 'NZD', 'Oceania', 'OC', 'COK', NULL, NULL),
(54, 506, 'CR', 'cr', 'Costa Rica', '₡', 'San Jose', 'Costa Rican Colon', 'CRC', 'North America', 'NA', 'CRI', NULL, NULL),
(55, 225, 'CI', 'ci', 'Cote D\'Ivoire', 'CFA', 'Yamoussoukro', 'CFA Franc BCEAO', 'XOF', 'Africa', 'AF', 'CIV', NULL, NULL),
(56, 385, 'HR', 'hr', 'Croatia', 'kn', 'Zagreb', 'Kuna', 'HRK', 'Europe', 'EU', 'HRV', NULL, NULL),
(57, 53, 'CU', 'cu', 'Cuba', '$', 'Havana', 'Cuban Peso', 'CUP', 'North America', 'NA', 'CUB', NULL, NULL),
(58, 599, 'CW', 'cw', 'Curacao', 'ƒ', 'Willemstad', 'Netherlands Antillean Guilder', 'ANG', 'North America', 'NA', 'CUW', NULL, NULL),
(59, 357, 'CY', 'cy', 'Cyprus', '€', 'Nicosia', 'Euro', 'EUR', 'Asia', 'AS', 'CYP', NULL, NULL),
(60, 420, 'CZ', 'cz', 'Czech Republic', 'Kč', 'Prague', '', 'CZK', 'Europe', 'EU', 'CZE', NULL, NULL),
(61, 45, 'DK', 'dk', 'Denmark', 'Kr.', 'Copenhagen', 'Danish Krone', 'DKK', 'Europe', 'EU', 'DNK', NULL, NULL),
(62, 253, 'DJ', 'dj', 'Djibouti', 'Fdj', 'Djibouti', 'Djibouti Franc', 'DJF', 'Africa', 'AF', 'DJI', NULL, NULL),
(63, 1767, 'DM', 'dm', 'Dominica', '$', 'Roseau', 'East Caribbean Dollar', 'XCD', 'North America', 'NA', 'DMA', NULL, NULL),
(64, 1809, 'DO', 'do', 'Dominican Republic', '$', 'Santo Domingo', 'Dominican Peso', 'DOP', 'North America', 'NA', 'DOM', NULL, NULL),
(65, 593, 'EC', 'ec', 'Ecuador', '$', 'Quito', 'US Dollar', 'USD', 'South America', 'SA', 'ECU', NULL, NULL),
(66, 20, 'EG', 'eg', 'Egypt', 'ج.م', 'Cairo', 'Egyptian Pound', 'EGP', 'Africa', 'AF', 'EGY', NULL, NULL),
(67, 503, 'SV', 'sv', 'El Salvador', '$', 'San Salvador', 'El Salvador Colon', 'USD', 'North America', 'NA', 'SLV', NULL, NULL),
(68, 240, 'GQ', 'gq', 'Equatorial Guinea', 'FCFA', 'Malabo', 'CFA Franc BEAC', 'XAF', 'Africa', 'AF', 'GNQ', NULL, NULL),
(69, 291, 'ER', 'er', 'Eritrea', 'Nfk', 'Asmara', 'Nakfa', 'ERN', 'Africa', 'AF', 'ERI', NULL, NULL),
(70, 372, 'EE', 'ee', 'Estonia', '€', 'Tallinn', 'Euro', 'EUR', 'Europe', 'EU', 'EST', NULL, NULL),
(71, 251, 'ET', 'et', 'Ethiopia', 'Nkf', 'Addis Ababa', 'Ethiopian Birr', 'ETB', 'Africa', 'AF', 'ETH', NULL, NULL),
(72, 500, 'FK', 'fk', 'Falkland Islands (Malvinas)', '£', 'Stanley', '', 'FKP', 'South America', 'SA', 'FLK', NULL, NULL),
(73, 298, 'FO', 'fo', 'Faroe Islands', 'Kr.', 'Torshavn', 'Danish Krone', 'DKK', 'Europe', 'EU', 'FRO', NULL, NULL),
(74, 679, 'FJ', 'fj', 'Fiji', 'FJ$', 'Suva', 'Fiji Dollar', 'FJD', 'Oceania', 'OC', 'FJI', NULL, NULL),
(75, 358, 'FI', 'fi', 'Finland', '€', 'Helsinki', 'Euro', 'EUR', 'Europe', 'EU', 'FIN', NULL, NULL),
(76, 33, 'FR', 'fr', 'France', '€', 'Paris', 'Euro', 'EUR', 'Europe', 'EU', 'FRA', NULL, NULL),
(77, 594, 'GF', 'gf', 'French Guiana', '€', 'Cayenne', 'Euro', 'EUR', 'South America', 'SA', 'GUF', NULL, NULL),
(78, 689, 'PF', 'pf', 'French Polynesia', '₣', 'Papeete', 'CFP Franc', 'XPF', 'Oceania', 'OC', 'PYF', NULL, NULL),
(79, 262, 'TF', 'tf', 'French Southern Territories', '€', 'Port-aux-Francais', 'Euro', 'EUR', 'Antarctica', 'AN', 'ATF', NULL, NULL),
(80, 241, 'GA', 'ga', 'Gabon', 'FCFA', 'Libreville', 'CFA Franc BEAC', 'XAF', 'Africa', 'AF', 'GAB', NULL, NULL),
(81, 220, 'GM', 'gm', 'Gambia', 'D', 'Banjul', 'Dalasi', 'GMD', 'Africa', 'AF', 'GMB', NULL, NULL),
(82, 995, 'GE', 'ge', 'Georgia', 'ლ', 'Tbilisi', 'Lari', 'GEL', 'Asia', 'AS', 'GEO', NULL, NULL),
(83, 49, 'DE', 'de', 'Germany', '€', 'Berlin', 'Euro', 'EUR', 'Europe', 'EU', 'DEU', NULL, NULL),
(84, 233, 'GH', 'gh', 'Ghana', 'GH₵', 'Accra', 'Ghana Cedi', 'GHS', 'Africa', 'AF', 'GHA', NULL, NULL),
(85, 350, 'GI', 'gi', 'Gibraltar', '£', 'Gibraltar', 'Gibraltar Pound', 'GIP', 'Europe', 'EU', 'GIB', NULL, NULL),
(86, 30, 'GR', 'gr', 'Greece', '€', 'Athens', 'Euro', 'EUR', 'Europe', 'EU', 'GRC', NULL, NULL),
(87, 299, 'GL', 'gl', 'Greenland', 'Kr.', 'Nuuk', 'Danish Krone', 'DKK', 'North America', 'NA', 'GRL', NULL, NULL),
(88, 1473, 'GD', 'gd', 'Grenada', '$', 'St. George\'s', 'East Caribbean Dollar', 'XCD', 'North America', 'NA', 'GRD', NULL, NULL),
(89, 590, 'GP', 'gp', 'Guadeloupe', '€', 'Basse-Terre', 'Euro', 'EUR', 'North America', 'NA', 'GLP', NULL, NULL),
(90, 1671, 'GU', 'gu', 'Guam', '$', 'Hagatna', 'US Dollar', 'USD', 'Oceania', 'OC', 'GUM', NULL, NULL),
(91, 502, 'GT', 'gt', 'Guatemala', 'Q', 'Guatemala City', 'Quetzal', 'GTQ', 'North America', 'NA', 'GTM', NULL, NULL),
(92, 44, 'GG', 'gg', 'Guernsey', '£', 'St Peter Port', 'Pound Sterling', 'GBP', 'Europe', 'EU', 'GGY', NULL, NULL),
(93, 224, 'GN', 'gn', 'Guinea', 'FG', 'Conakry', 'Kina', 'GNF', 'Africa', 'AF', 'GIN', NULL, NULL),
(94, 245, 'GW', 'gw', 'Guinea-Bissau', 'CFA', 'Bissau', 'CFA Franc BCEAO', 'XOF', 'Africa', 'AF', 'GNB', NULL, NULL),
(95, 592, 'GY', 'gy', 'Guyana', '$', 'Georgetown', 'Guyana Dollar', 'GYD', 'South America', 'SA', 'GUY', NULL, NULL),
(96, 509, 'HT', 'ht', 'Haiti', 'G', 'Port-au-Prince', 'Gourde', 'HTG', 'North America', 'NA', 'HTI', NULL, NULL),
(97, 0, 'HM', 'hm', 'Heard Island and Mcdonald Islands', '$', '', 'Australian Dollar', 'AUD', 'Antarctica', 'AN', 'HMD', NULL, NULL),
(98, 39, 'VA', 'va', 'Holy See (Vatican City State)', '€', 'Vatican City', '', 'EUR', 'Europe', 'EU', 'VAT', NULL, NULL),
(99, 504, 'HN', 'hn', 'Honduras', 'L', 'Tegucigalpa', 'Lempira', 'HNL', 'North America', 'NA', 'HND', NULL, NULL),
(100, 852, 'HK', 'hk', 'Hong Kong', '$', 'Hong Kong', 'Hong Kong Dollar', 'HKD', 'Asia', 'AS', 'HKG', NULL, NULL),
(101, 36, 'HU', 'hu', 'Hungary', 'Ft', 'Budapest', 'Forint', 'HUF', 'Europe', 'EU', 'HUN', NULL, NULL),
(102, 354, 'IS', 'is', 'Iceland', 'kr', 'Reykjavik', 'Iceland Krona', 'ISK', 'Europe', 'EU', 'ISL', NULL, NULL),
(103, 91, 'IN', 'in', 'India', '₹', 'New Delhi', 'Indian Rupee ', 'INR', 'Asia', 'AS', 'IND', NULL, NULL),
(104, 62, 'ID', 'id', 'Indonesia', 'Rp', 'Jakarta', 'Rupiah', 'IDR', 'Asia', 'AS', 'IDN', NULL, NULL),
(105, 98, 'IR', 'ir', 'Iran, Islamic Republic of', '﷼', 'Tehran', '', 'IRR', 'Asia', 'AS', 'IRN', NULL, NULL),
(106, 964, 'IQ', 'iq', 'Iraq', 'د.ع', 'Baghdad', 'Iraqi Dinar', 'IQD', 'Asia', 'AS', 'IRQ', NULL, NULL),
(107, 353, 'IE', 'ie', 'Ireland', '€', 'Dublin', 'Euro', 'EUR', 'Europe', 'EU', 'IRL', NULL, NULL),
(108, 44, 'IM', 'im', 'Isle of Man', '£', 'Douglas, Isle of Man', 'Pound Sterling', 'GBP', 'Europe', 'EU', 'IMN', NULL, NULL),
(109, 972, 'IL', 'il', 'Israel', '₪', 'Jerusalem', 'New Israeli Sheqel', 'ILS', 'Asia', 'AS', 'ISR', NULL, NULL),
(110, 39, 'IT', 'it', 'Italy', '€', 'Rome', 'Euro', 'EUR', 'Europe', 'EU', 'ITA', NULL, NULL),
(111, 1876, 'JM', 'jm', 'Jamaica', 'J$', 'Kingston', 'Jamaican Dollar', 'JMD', 'North America', 'NA', 'JAM', NULL, NULL),
(112, 81, 'JP', 'jp', 'Japan', '¥', 'Tokyo', 'Yen', 'JPY', 'Asia', 'AS', 'JPN', NULL, NULL),
(113, 44, 'JE', 'je', 'Jersey', '£', 'Saint Helier', 'Pound Sterling', 'GBP', 'Europe', 'EU', 'JEY', NULL, NULL),
(114, 962, 'JO', 'jo', 'Jordan', 'ا.د', 'Amman', 'Jordanian Dinar', 'JOD', 'Asia', 'AS', 'JOR', NULL, NULL),
(115, 7, 'KZ', 'kz', 'Kazakhstan', 'лв', 'Astana', 'Tenge', 'KZT', 'Asia', 'AS', 'KAZ', NULL, NULL),
(116, 254, 'KE', 'ke', 'Kenya', 'KSh', 'Nairobi', 'Kenyan Shilling', 'KES', 'Africa', 'AF', 'KEN', NULL, NULL),
(117, 686, 'KI', 'ki', 'Kiribati', '$', 'Tarawa', 'Australian Dollar', 'AUD', 'Oceania', 'OC', 'KIR', NULL, NULL),
(118, 850, 'KP', 'kp', 'Korea, Democratic People\'s Republic of', '₩', 'Pyongyang', '', 'KPW', 'Asia', 'AS', 'PRK', NULL, NULL),
(119, 82, 'KR', 'kr', 'Korea, Republic of', '₩', 'Seoul', '', 'KRW', 'Asia', 'AS', 'KOR', NULL, NULL),
(120, 381, 'XK', 'xk', 'Kosovo', '€', 'Pristina', '', 'EUR', 'Europe', 'EU', 'XKX', NULL, NULL),
(121, 965, 'KW', 'kw', 'Kuwait', 'ك.د', 'Kuwait City', 'Kuwaiti Dinar', 'KWD', 'Asia', 'AS', 'KWT', NULL, NULL),
(122, 996, 'KG', 'kg', 'Kyrgyzstan', 'лв', 'Bishkek', 'Som', 'KGS', 'Asia', 'AS', 'KGZ', NULL, NULL),
(123, 856, 'LA', 'la', 'Lao People\'s Democratic Republic', '₭', 'Vientiane', '', 'LAK', 'Asia', 'AS', 'LAO', NULL, NULL),
(124, 371, 'LV', 'lv', 'Latvia', '€', 'Riga', 'Euro', 'EUR', 'Europe', 'EU', 'LVA', NULL, NULL),
(125, 961, 'LB', 'lb', 'Lebanon', '£', 'Beirut', 'Lebanese Pound', 'LBP', 'Asia', 'AS', 'LBN', NULL, NULL),
(126, 266, 'LS', 'ls', 'Lesotho', 'L', 'Maseru', 'Loti', 'LSL', 'Africa', 'AF', 'LSO', NULL, NULL),
(127, 231, 'LR', 'lr', 'Liberia', '$', 'Monrovia', 'Liberian Dollar', 'LRD', 'Africa', 'AF', 'LBR', NULL, NULL),
(128, 218, 'LY', 'ly', 'Libyan Arab Jamahiriya', 'د.ل', 'Tripolis', '', 'LYD', 'Africa', 'AF', 'LBY', NULL, NULL),
(129, 423, 'LI', 'li', 'Liechtenstein', 'CHf', 'Vaduz', 'Swiss Franc', 'CHF', 'Europe', 'EU', 'LIE', NULL, NULL),
(130, 370, 'LT', 'lt', 'Lithuania', '€', 'Vilnius', 'Euro', 'EUR', 'Europe', 'EU', 'LTU', NULL, NULL),
(131, 352, 'LU', 'lu', 'Luxembourg', '€', 'Luxembourg', 'Euro', 'EUR', 'Europe', 'EU', 'LUX', NULL, NULL),
(132, 853, 'MO', 'mo', 'Macao', '$', 'Macao', 'Pataca', 'MOP', 'Asia', 'AS', 'MAC', NULL, NULL),
(133, 389, 'MK', 'mk', 'Macedonia, the Former Yugoslav Republic of', 'ден', 'Skopje', '', 'MKD', 'Europe', 'EU', 'MKD', NULL, NULL),
(134, 261, 'MG', 'mg', 'Madagascar', 'Ar', 'Antananarivo', 'Malagasy Ariary', 'MGA', 'Africa', 'AF', 'MDG', NULL, NULL),
(135, 265, 'MW', 'mw', 'Malawi', 'MK', 'Lilongwe', 'Malawi Kwacha', 'MWK', 'Africa', 'AF', 'MWI', NULL, NULL),
(136, 60, 'MY', 'my', 'Malaysia', 'RM', 'Kuala Lumpur', 'Malaysian Ringgit', 'MYR', 'Asia', 'AS', 'MYS', NULL, NULL),
(137, 960, 'MV', 'mv', 'Maldives', 'Rf', 'Male', 'Rufiyaa', 'MVR', 'Asia', 'AS', 'MDV', NULL, NULL),
(138, 223, 'ML', 'ml', 'Mali', 'CFA', 'Bamako', 'CFA Franc BCEAO', 'XOF', 'Africa', 'AF', 'MLI', NULL, NULL),
(139, 356, 'MT', 'mt', 'Malta', '€', 'Valletta', 'Euro', 'EUR', 'Europe', 'EU', 'MLT', NULL, NULL),
(140, 692, 'MH', 'mh', 'Marshall Islands', '$', 'Majuro', 'US Dollar', 'USD', 'Oceania', 'OC', 'MHL', NULL, NULL),
(141, 596, 'MQ', 'mq', 'Martinique', '€', 'Fort-de-France', 'Euro', 'EUR', 'North America', 'NA', 'MTQ', NULL, NULL),
(142, 222, 'MR', 'mr', 'Mauritania', 'MRU', 'Nouakchott', 'Ouguiya', 'MRO', 'Africa', 'AF', 'MRT', NULL, NULL),
(143, 230, 'MU', 'mu', 'Mauritius', '₨', 'Port Louis', 'Mauritius Rupee', 'MUR', 'Africa', 'AF', 'MUS', NULL, NULL),
(144, 269, 'YT', 'yt', 'Mayotte', '€', 'Mamoudzou', 'Euro', 'EUR', 'Africa', 'AF', 'MYT', NULL, NULL),
(145, 52, 'MX', 'mx', 'Mexico', '$', 'Mexico City', 'Mexican Peso', 'MXN', 'North America', 'NA', 'MEX', NULL, NULL),
(146, 691, 'FM', 'fm', 'Micronesia, Federated States of', '$', 'Palikir', '', 'USD', 'Oceania', 'OC', 'FSM', NULL, NULL),
(147, 373, 'MD', 'md', 'Moldova, Republic of', 'L', 'Chisinau', '', 'MDL', 'Europe', 'EU', 'MDA', NULL, NULL),
(148, 377, 'MC', 'mc', 'Monaco', '€', 'Monaco', 'Euro', 'EUR', 'Europe', 'EU', 'MCO', NULL, NULL),
(149, 976, 'MN', 'mn', 'Mongolia', '₮', 'Ulan Bator', 'Tugrik', 'MNT', 'Asia', 'AS', 'MNG', NULL, NULL),
(150, 382, 'ME', 'me', 'Montenegro', '€', 'Podgorica', 'Euro', 'EUR', 'Europe', 'EU', 'MNE', NULL, NULL),
(151, 1664, 'MS', 'ms', 'Montserrat', '$', 'Plymouth', 'East Caribbean Dollar', 'XCD', 'North America', 'NA', 'MSR', NULL, NULL),
(152, 212, 'MA', 'ma', 'Morocco', 'DH', 'Rabat', 'Moroccan Dirham', 'MAD', 'Africa', 'AF', 'MAR', NULL, NULL),
(153, 258, 'MZ', 'mz', 'Mozambique', 'MT', 'Maputo', 'Mozambique Metical', 'MZN', 'Africa', 'AF', 'MOZ', NULL, NULL),
(154, 95, 'MM', 'mm', 'Myanmar', 'K', 'Nay Pyi Taw', 'Kyat', 'MMK', 'Asia', 'AS', 'MMR', NULL, NULL),
(155, 264, 'NA', 'na', 'Namibia', '$', 'Windhoek', 'Namibia Dollar', 'NAD', 'Africa', 'AF', 'NAM', NULL, NULL),
(156, 674, 'NR', 'nr', 'Nauru', '$', 'Yaren', 'Australian Dollar', 'AUD', 'Oceania', 'OC', 'NRU', NULL, NULL),
(157, 977, 'NP', 'np', 'Nepal', '₨', 'Kathmandu', 'Nepalese Rupee', 'NPR', 'Asia', 'AS', 'NPL', NULL, NULL),
(158, 31, 'NL', 'nl', 'Netherlands', '€', 'Amsterdam', 'Euro', 'EUR', 'Europe', 'EU', 'NLD', NULL, NULL),
(159, 599, 'AN', 'an', 'Netherlands Antilles', 'NAf', 'Willemstad', '', 'ANG', 'North America', 'NA', 'ANT', NULL, NULL),
(160, 687, 'NC', 'nc', 'New Caledonia', '₣', 'Noumea', 'CFP Franc', 'XPF', 'Oceania', 'OC', 'NCL', NULL, NULL),
(161, 64, 'NZ', 'nz', 'New Zealand', '$', 'Wellington', 'New Zealand Dollar', 'NZD', 'Oceania', 'OC', 'NZL', NULL, NULL),
(162, 505, 'NI', 'ni', 'Nicaragua', 'C$', 'Managua', 'Cordoba Oro', 'NIO', 'North America', 'NA', 'NIC', NULL, NULL),
(163, 227, 'NE', 'ne', 'Niger', 'CFA', 'Niamey', 'CFA Franc BCEAO', 'XOF', 'Africa', 'AF', 'NER', NULL, NULL),
(164, 234, 'NG', 'ng', 'Nigeria', '₦', 'Abuja', 'Naira', 'NGN', 'Africa', 'AF', 'NGA', NULL, NULL),
(165, 683, 'NU', 'nu', 'Niue', '$', 'Alofi', 'New Zealand Dollar', 'NZD', 'Oceania', 'OC', 'NIU', NULL, NULL),
(166, 672, 'NF', 'nf', 'Norfolk Island', '$', 'Kingston', 'Australian Dollar', 'AUD', 'Oceania', 'OC', 'NFK', NULL, NULL),
(167, 1670, 'MP', 'mp', 'Northern Mariana Islands', '$', 'Saipan', 'US Dollar', 'USD', 'Oceania', 'OC', 'MNP', NULL, NULL),
(168, 47, 'NO', 'no', 'Norway', 'kr', 'Oslo', 'Norwegian Krone', 'NOK', 'Europe', 'EU', 'NOR', NULL, NULL),
(169, 968, 'OM', 'om', 'Oman', '.ع.ر', 'Muscat', 'Rial Omani', 'OMR', 'Asia', 'AS', 'OMN', NULL, NULL),
(170, 92, 'PK', 'pk', 'Pakistan', '₨', 'Islamabad', 'Pakistan Rupee', 'PKR', 'Asia', 'AS', 'PAK', NULL, NULL),
(171, 680, 'PW', 'pw', 'Palau', '$', 'Melekeok', 'US Dollar', 'USD', 'Oceania', 'OC', 'PLW', NULL, NULL),
(172, 970, 'PS', 'ps', 'Palestinian Territory, Occupied', '₪', 'East Jerusalem', '', 'ILS', 'Asia', 'AS', 'PSE', NULL, NULL),
(173, 507, 'PA', 'pa', 'Panama', 'B/.', 'Panama City', 'Balboa', 'PAB', 'North America', 'NA', 'PAN', NULL, NULL),
(174, 675, 'PG', 'pg', 'Papua New Guinea', 'K', 'Port Moresby', 'Kina', 'PGK', 'Oceania', 'OC', 'PNG', NULL, NULL),
(175, 595, 'PY', 'py', 'Paraguay', '₲', 'Asuncion', 'Guarani', 'PYG', 'South America', 'SA', 'PRY', NULL, NULL),
(176, 51, 'PE', 'pe', 'Peru', 'S/.', 'Lima', 'Sol', 'PEN', 'South America', 'SA', 'PER', NULL, NULL),
(177, 63, 'PH', 'ph', 'Philippines', '₱', 'Manila', 'Philippine Peso', 'PHP', 'Asia', 'AS', 'PHL', NULL, NULL),
(178, 64, 'PN', 'pn', 'Pitcairn', '$', 'Adamstown', 'New Zealand Dollar', 'NZD', 'Oceania', 'OC', 'PCN', NULL, NULL),
(179, 48, 'PL', 'pl', 'Poland', 'zł', 'Warsaw', 'Zloty', 'PLN', 'Europe', 'EU', 'POL', NULL, NULL),
(180, 351, 'PT', 'pt', 'Portugal', '€', 'Lisbon', 'Euro', 'EUR', 'Europe', 'EU', 'PRT', NULL, NULL),
(181, 1787, 'PR', 'pr', 'Puerto Rico', '$', 'San Juan', 'US Dollar', 'USD', 'North America', 'NA', 'PRI', NULL, NULL),
(182, 974, 'QA', 'qa', 'Qatar', 'ق.ر', 'Doha', 'Qatari Rial', 'QAR', 'Asia', 'AS', 'QAT', NULL, NULL),
(183, 262, 'RE', 're', 'Reunion', '€', 'Saint-Denis', 'Euro', 'EUR', 'Africa', 'AF', 'REU', NULL, NULL),
(184, 40, 'RO', 'ro', 'Romania', 'lei', 'Bucharest', 'Romanian Leu', 'RON', 'Europe', 'EU', 'ROM', NULL, NULL),
(185, 70, 'RU', 'ru', 'Russian Federation', '₽', 'Moscow', 'Russian Ruble', 'RUB', 'Asia', 'AS', 'RUS', NULL, NULL),
(186, 250, 'RW', 'rw', 'Rwanda', 'FRw', 'Kigali', 'Rwanda Franc', 'RWF', 'Africa', 'AF', 'RWA', NULL, NULL),
(187, 590, 'BL', 'bl', 'Saint Barthelemy', '€', 'Gustavia', 'Euro', 'EUR', 'North America', 'NA', 'BLM', NULL, NULL),
(188, 290, 'SH', 'sh', 'Saint Helena', '£', 'Jamestown', 'Saint Helena Pound', 'SHP', 'Africa', 'AF', 'SHN', NULL, NULL),
(189, 1869, 'KN', 'kn', 'Saint Kitts and Nevis', '$', 'Basseterre', 'East Caribbean Dollar', 'XCD', 'North America', 'NA', 'KNA', NULL, NULL),
(190, 1758, 'LC', 'lc', 'Saint Lucia', '$', 'Castries', 'East Caribbean Dollar', 'XCD', 'North America', 'NA', 'LCA', NULL, NULL),
(191, 590, 'MF', 'mf', 'Saint Martin', '€', 'Marigot', 'Euro', 'EUR', 'North America', 'NA', 'MAF', NULL, NULL),
(192, 508, 'PM', 'pm', 'Saint Pierre and Miquelon', '€', 'Saint-Pierre', 'Euro', 'EUR', 'North America', 'NA', 'SPM', NULL, NULL),
(193, 1784, 'VC', 'vc', 'Saint Vincent and the Grenadines', '$', 'Kingstown', 'East Caribbean Dollar', 'XCD', 'North America', 'NA', 'VCT', NULL, NULL),
(194, 684, 'WS', 'ws', 'Samoa', 'SAT', 'Apia', 'US Dollar', 'WST', 'Oceania', 'OC', 'WSM', NULL, NULL),
(195, 378, 'SM', 'sm', 'San Marino', '€', 'San Marino', 'Euro', 'EUR', 'Europe', 'EU', 'SMR', NULL, NULL),
(196, 239, 'ST', 'st', 'Sao Tome and Principe', 'Db', 'Sao Tome', 'Dobra', 'STD', 'Africa', 'AF', 'STP', NULL, NULL),
(197, 966, 'SA', 'sa', 'Saudi Arabia', '﷼', 'Riyadh', 'Saudi Riyal', 'SAR', 'Asia', 'AS', 'SAU', NULL, NULL),
(198, 221, 'SN', 'sn', 'Senegal', 'CFA', 'Dakar', 'CFA Franc BCEAO', 'XOF', 'Africa', 'AF', 'SEN', NULL, NULL),
(199, 381, 'RS', 'rs', 'Serbia', 'din', 'Belgrade', 'Serbian Dinar', 'RSD', 'Europe', 'EU', 'SRB', NULL, NULL),
(200, 381, 'CS', 'cs', 'Serbia and Montenegro', 'din', 'Belgrade', '', 'RSD', 'Europe', 'EU', 'SCG', NULL, NULL),
(201, 248, 'SC', 'sc', 'Seychelles', 'SRe', 'Victoria', 'Seychelles Rupee', 'SCR', 'Africa', 'AF', 'SYC', NULL, NULL),
(202, 232, 'SL', 'sl', 'Sierra Leone', 'Le', 'Freetown', 'Leone', 'SLL', 'Africa', 'AF', 'SLE', NULL, NULL),
(203, 65, 'SG', 'sg', 'Singapore', '$', 'Singapur', 'Singapore Dollar', 'SGD', 'Asia', 'AS', 'SGP', NULL, NULL),
(204, 1, 'SX', 'sx', 'Sint Maarten', 'ƒ', 'Philipsburg', 'Netherlands Antillean Guilder', 'ANG', 'North America', 'NA', 'SXM', NULL, NULL),
(205, 421, 'SK', 'sk', 'Slovakia', '€', 'Bratislava', 'Euro', 'EUR', 'Europe', 'EU', 'SVK', NULL, NULL),
(206, 386, 'SI', 'si', 'Slovenia', '€', 'Ljubljana', 'Euro', 'EUR', 'Europe', 'EU', 'SVN', NULL, NULL),
(207, 677, 'SB', 'sb', 'Solomon Islands', 'Si$', 'Honiara', 'Solomon Islands Dollar', 'SBD', 'Oceania', 'OC', 'SLB', NULL, NULL),
(208, 252, 'SO', 'so', 'Somalia', 'Sh.so.', 'Mogadishu', 'Somali Shilling', 'SOS', 'Africa', 'AF', 'SOM', NULL, NULL),
(209, 27, 'ZA', 'za', 'South Africa', 'R', 'Pretoria', 'Rand', 'ZAR', 'Africa', 'AF', 'ZAF', NULL, NULL),
(210, 500, 'GS', 'gs', 'South Georgia and the South Sandwich Islands', '£', 'Grytviken', '', 'GBP', 'Antarctica', 'AN', 'SGS', NULL, NULL),
(211, 211, 'SS', 'ss', 'South Sudan', '£', 'Juba', 'South Sudanese Pound', 'SSP', 'Africa', 'AF', 'SSD', NULL, NULL),
(212, 34, 'ES', 'es', 'Spain', '€', 'Madrid', 'Euro', 'EUR', 'Europe', 'EU', 'ESP', NULL, NULL),
(213, 94, 'LK', 'lk', 'Sri Lanka', 'Rs', 'Colombo', 'Sri Lanka Rupee', 'LKR', 'Asia', 'AS', 'LKA', NULL, NULL),
(214, 249, 'SD', 'sd', 'Sudan', '.س.ج', 'Khartoum', 'South Sudanese Pound', 'SDG', 'Africa', 'AF', 'SDN', NULL, NULL),
(215, 597, 'SR', 'sr', 'Suriname', '$', 'Paramaribo', 'Surinam Dollar', 'SRD', 'South America', 'SA', 'SUR', NULL, NULL),
(216, 47, 'SJ', 'sj', 'Svalbard and Jan Mayen', 'kr', 'Longyearbyen', 'Norwegian Krone', 'NOK', 'Europe', 'EU', 'SJM', NULL, NULL),
(217, 268, 'SZ', 'sz', 'Swaziland', 'E', 'Mbabane', '', 'SZL', 'Africa', 'AF', 'SWZ', NULL, NULL),
(218, 46, 'SE', 'se', 'Sweden', 'kr', 'Stockholm', 'Swedish Krona', 'SEK', 'Europe', 'EU', 'SWE', NULL, NULL),
(219, 41, 'CH', 'ch', 'Switzerland', 'CHf', 'Berne', 'Swiss Franc', 'CHF', 'Europe', 'EU', 'CHE', NULL, NULL),
(220, 963, 'SY', 'sy', 'Syrian Arab Republic', 'LS', 'Damascus', 'Syrian Pound', 'SYP', 'Asia', 'AS', 'SYR', NULL, NULL),
(221, 886, 'TW', 'tw', 'Taiwan, Province of China', '$', 'Taipei', '', 'TWD', 'Asia', 'AS', 'TWN', NULL, NULL),
(222, 992, 'TJ', 'tj', 'Tajikistan', 'SM', 'Dushanbe', 'Somoni', 'TJS', 'Asia', 'AS', 'TJK', NULL, NULL),
(223, 255, 'TZ', 'tz', 'Tanzania, United Republic of', 'TSh', 'Dodoma', 'Tanzanian Shilling', 'TZS', 'Africa', 'AF', 'TZA', NULL, NULL),
(224, 66, 'TH', 'th', 'Thailand', '฿', 'Bangkok', 'Baht', 'THB', 'Asia', 'AS', 'THA', NULL, NULL),
(225, 670, 'TL', 'tl', 'Timor-Leste', '$', 'Dili', 'US Dollar', 'USD', 'Asia', 'AS', 'TLS', NULL, NULL),
(226, 228, 'TG', 'tg', 'Togo', 'CFA', 'Lome', 'CFA Franc BCEAO', 'XOF', 'Africa', 'AF', 'TGO', NULL, NULL),
(227, 690, 'TK', 'tk', 'Tokelau', '$', '', 'New Zealand Dollar', 'NZD', 'Oceania', 'OC', 'TKL', NULL, NULL),
(228, 676, 'TO', 'to', 'Tonga', '$', 'Nuku\alofa', 'Paanga', 'TOP', 'Oceania', 'OC', 'TON', NULL, NULL),
(229, 1868, 'TT', 'tt', 'Trinidad and Tobago', '$', 'Port of Spain', 'Trinidad and Tobago Dollar', 'TTD', 'North America', 'NA', 'TTO', NULL, NULL),
(230, 216, 'TN', 'tn', 'Tunisia', 'ت.د', 'Tunis', 'Tunisian Dinar', 'TND', 'Africa', 'AF', 'TUN', NULL, NULL),
(231, 90, 'TR', 'tr', 'Turkey', '₺', 'Ankara', 'Turkish Lira', 'TRY', 'Asia', 'AS', 'TUR', NULL, NULL),
(232, 7370, 'TM', 'tm', 'Turkmenistan', 'T', 'Ashgabat', 'Turkmenistan New Manat', 'TMT', 'Asia', 'AS', 'TKM', NULL, NULL),
(233, 1649, 'TC', 'tc', 'Turks and Caicos Islands', '$', 'Cockburn Town', 'US Dollar', 'USD', 'North America', 'NA', 'TCA', NULL, NULL),
(234, 688, 'TV', 'tv', 'Tuvalu', '$', 'Funafuti', 'Australian Dollar', 'AUD', 'Oceania', 'OC', 'TUV', NULL, NULL),
(235, 256, 'UG', 'ug', 'Uganda', 'USh', 'Kampala', 'Uganda Shilling', 'UGX', 'Africa', 'AF', 'UGA', NULL, NULL),
(236, 380, 'UA', 'ua', 'Ukraine', '₴', 'Kiev', 'Hryvnia', 'UAH', 'Europe', 'EU', 'UKR', NULL, NULL),
(237, 971, 'AE', 'ae', 'United Arab Emirates', 'إ.د', 'Abu Dhabi', 'UAE Dirham', 'AED', 'Asia', 'AS', 'ARE', NULL, NULL),
(238, 44, 'GB', 'gb', 'United Kingdom', '£', 'London', 'Pound Sterling', 'GBP', 'Europe', 'EU', 'GBR', NULL, NULL),
(239, 1, 'US', 'us', 'United States', '$', 'Washington', 'US Dollar', 'USD', 'North America', 'NA', 'USA', NULL, NULL),
(240, 1, 'UM', 'um', 'United States Minor Outlying Islands', '$', '', 'US Dollar', 'USD', 'North America', 'NA', 'UMI', NULL, NULL),
(241, 598, 'UY', 'uy', 'Uruguay', '$', 'Montevideo', 'Peso Uruguayo', 'UYU', 'South America', 'SA', 'URY', NULL, NULL),
(242, 998, 'UZ', 'uz', 'Uzbekistan', 'лв', 'Tashkent', 'Uzbekistan Sum', 'UZS', 'Asia', 'AS', 'UZB', NULL, NULL),
(243, 678, 'VU', 'vu', 'Vanuatu', 'VT', 'Port Vila', 'Vatu', 'VUV', 'Oceania', 'OC', 'VUT', NULL, NULL),
(244, 58, 'VE', 've', 'Venezuela', 'Bs', 'Caracas', 'Bolívar Soberano', 'VEF', 'South America', 'SA', 'VEN', NULL, NULL),
(245, 84, 'VN', 'vn', 'Viet Nam', '₫', 'Hanoi', '', 'VND', 'Asia', 'AS', 'VNM', NULL, NULL),
(246, 1284, 'VG', 'vg', 'Virgin Islands, British', '$', 'Road Town', '', 'USD', 'North America', 'NA', 'VGB', NULL, NULL),
(247, 1340, 'VI', 'vi', 'Virgin Islands, U.s.', '$', 'Charlotte Amalie', '', 'USD', 'North America', 'NA', 'VIR', NULL, NULL),
(248, 681, 'WF', 'wf', 'Wallis and Futuna', '₣', 'Mata Utu', 'CFP Franc', 'XPF', 'Oceania', 'OC', 'WLF', NULL, NULL),
(249, 212, 'EH', 'eh', 'Western Sahara', 'MAD', 'El-Aaiun', 'Moroccan Dirham', 'MAD', 'Africa', 'AF', 'ESH', NULL, NULL),
(250, 967, 'YE', 'ye', 'Yemen', '﷼', 'Sanaa', 'Yemeni Rial', 'YER', 'Asia', 'AS', 'YEM', NULL, NULL),
(251, 260, 'ZM', 'zm', 'Zambia', 'ZK', 'Lusaka', 'Zambian Kwacha', 'ZMW', 'Africa', 'AF', 'ZMB', NULL, NULL),
(252, 263, 'ZW', 'zw', 'Zimbabwe', '$', 'Harare', 'Zimbabwe Dollar', 'ZWL', 'Africa', 'AF', 'ZWE', NULL, NULL);

--
-- Indexes for table `countries`
--
ALTER TABLE `countries`
  ADD PRIMARY KEY (`id`);


--
-- AUTO_INCREMENT for table `countries`
--
ALTER TABLE `countries`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;
COMMIT;