on:
  push:
    branches: 
      - production
      
name: Deploy to Cpanel From GitHub
jobs: 
  web-deploy: 
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the Latest Codes
        uses: actions/checkout@v3
        
      - name: Synch FIles
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          server-dir: /public_html/
          protocol: ftp

